import { validateCategoryPack, validateConfigPack, validateFilesPack, validateInterfacePack, validateScriptPack } from '#lostcity/util/Pack.js';

console.time('validate');
const PACKFILE = new Map<string, string[]>();
PACKFILE.set('anim', validateFilesPack('data/pack/anim.pack', 'data/src/models', '.frame'));
PACKFILE.set('base', validateFilesPack('data/pack/base.pack', 'data/src/models', '.base'));
PACKFILE.set('category', validateCategoryPack());
PACKFILE.set('dbrow', validateConfigPack('data/pack/dbrow.pack', '.dbrow', true));
PACKFILE.set('dbtable', validateConfigPack('data/pack/dbtable.pack', '.dbtable', true));
PACKFILE.set('enum', validateConfigPack('data/pack/enum.pack', '.enum', true));
PACKFILE.set('flo', validateConfigPack('data/pack/flo.pack', '.flo'));
PACKFILE.set('idk', validateConfigPack('data/pack/idk.pack', '.idk'));
PACKFILE.set('interface', validateInterfacePack());
PACKFILE.set('inv', validateConfigPack('data/pack/inv.pack', '.inv', true));
PACKFILE.set('loc', validateConfigPack('data/pack/loc.pack', '.loc'));
PACKFILE.set('mesanim', validateConfigPack('data/pack/mesanim.pack', '.mesanim', true));
PACKFILE.set('model', validateFilesPack('data/pack/model.pack', 'data/src/models', '.ob2'));
PACKFILE.set('npc', validateConfigPack('data/pack/npc.pack', '.npc'));
PACKFILE.set('obj', validateConfigPack('data/pack/obj.pack', '.obj'));
PACKFILE.set('param', validateConfigPack('data/pack/param.pack', '.param', true));
PACKFILE.set('script', validateScriptPack());
PACKFILE.set('seq', validateConfigPack('data/pack/seq.pack', '.seq'));
PACKFILE.set('sound', validateFilesPack('data/pack/sound.pack', 'data/src/sounds', '.synth'));
PACKFILE.set('spotanim', validateConfigPack('data/pack/spotanim.pack', '.spotanim'));
PACKFILE.set('struct', validateConfigPack('data/pack/struct.pack', '.struct', true));
PACKFILE.set('texture', validateFilesPack('data/pack/texture.pack', 'data/src/textures', '.png'));
PACKFILE.set('varp', validateConfigPack('data/pack/varp.pack', '.varp', true));
console.timeEnd('validate');
