export default {
    // textures archive

    textures: [
        'door',
        'water',
        'wall',
        'planks',
        'elfdoor',
        'darkwood',
        'roof',
        'damage',
        'leafytree',
        'treestump',
        'leafybase',
        'mossy',
        'railings',
        'painting1',
        'painting2',
        'marble',
        'wood2',
        'fountain',
        'thatched',
        'cargonet',
        'books',
        'elfroof2',
        'elfwood',
        'mossybricks',
        'water_animated',
        'gungywater',
        'web',
        'elfroof',
        'mossydamage',
        'bamboo',
        'willowtex3',
        'lava',
        'bark',
        'mapletree',
        'yewtree',
        'empty',
        'elfwall',
        'chainmail',
        'mummy',
        'elfpainting',
        'jungleleaf4',
        'plant',
        'jungleleaf2',
        'plant2',
        'roof2',
        'door2',
        'pebblefloor',
        'rockwall',
        'glyphs',
        'canvas'
    ],

    // media archive

    combatboxes: [
        'inactive',
        'active'
    ],

    combaticons: [
        'battleaxe_block',
        'battleaxe_chop',
        'battleaxe_hack',
        'battleaxe_smash',
        'sword_block',
        'sword_slash',
        'sword_chop',
        'sword_lunge',
        'spear_lunge',
        'spear_pound',
        'mace_block',
        'mace_pummel',
        'mace_spike',
        'mace_pound',
        'unarmed_punch',
        'unarmed_kick',
        'unarmed_block',
        'spear_block',
        'spear_swipe',
        'staff_block'
    ],

    combaticons2: [
        'warhammer_block',
        'warhammer_unused',
        'warhammer_pound',
        'warhammer_pummel',
        'crossbow_unused',
        'crossbow_accurate',
        'crossbow_rapid',
        'crossbow_longrange',
        'scythe_block',
        'scythe_chop',
        'thrown_accurate',
        'thrown_rapid',
        'thrown_longrange',
        'staff_bash',
        'staff_pound',
        'bow_accurate',
        'bow_rapid',
        'bow_longrange',
        'scythe_jab',
        'scythe_reap'
    ],

    combaticons3: [
        'pickaxe_block',
        'pickaxe_spike',
        'pickaxe_smash',
        'pickaxe_impale',
        'claws_luge',
        'claws_slash',
        'claws_chop',
        'claws_block'
    ],

    cross: [
        'click1',
        'click2',
        'click3',
        'click4',
        'action1',
        'action2',
        'action3',
        'action4'
    ],

    gnomeball_buttons: [
        'pass_to',
        'shoot',
        'tackle'
    ],

    headicons: [
        'skull',
        'multicombat',
        'hint',
        'protect_from_melee',
        'protect_from_ranged',
        'protect_from_magic',
        'duel',
        'hint_flash'
    ],

    hitmarks: [
        'blocked',
        'hit',
        'poison'
    ],

    magicoff: [
        'wind_strike',
        'confuse',
        'water_strike',
        'enchant_jewelry_sapphire',
        'earth_strike',
        'weaken',
        'fire_strike',
        'bones_to_bananas',
        'wind_bolt',
        'curse',
        'alchemy_low',
        'water_bolt',
        'teleport_varrock',
        'enchant_jewelry_emerald',
        'earth_bolt',
        'teleport_lumbridge',
        'telekinetic_grab',
        'fire_bolt',
        'teleport_falador',
        'crumble_undead',
        'wind_blast',
        'superheat_item',
        'teleport_camelot',
        'water_blast',
        'enchant_jewelry_ruby',
        'earth_blast',
        'alchemy_high',
        'charge_water_orb',
        'enchant_jewelry_diamond',
        'fire_blast',
        'charge_earth_orb',
        'wind_wave',
        'charge_fire_orb',
        'water_wave',
        'charge_air_orb',
        'enchant_jewelry_dragonstone',
        'earth_wave',
        'fire_wave',
        'iban_blast',
        'teleport_ardougne',
        'teleport_watchtower',
        'vulnerability',
        'enfeeble',
        'stun',
        'flames_of_zamorak',
        'claws_of_guthix',
        'saradomin_strike',
        'call_animal',
        'raise_undead',
        'summon_demon'
    ],

    magicoff2: [
        'bind',
        'snare',
        'entangle',
        'charge'
    ],

    magicon: [
        'wind_strike',
        'confuse',
        'water_strike',
        'enchant_jewelry_sapphire',
        'earth_strike',
        'weaken',
        'fire_strike',
        'bones_to_bananas',
        'wind_bolt',
        'curse',
        'alchemy_low',
        'water_bolt',
        'teleport_varrock',
        'enchant_jewelry_emerald',
        'earth_bolt',
        'teleport_lumbridge',
        'telekinetic_grab',
        'fire_bolt',
        'teleport_falador',
        'crumble_undead',
        'wind_blast',
        'superheat_item',
        'teleport_camelot',
        'water_blast',
        'enchant_jewelry_ruby',
        'earth_blast',
        'alchemy_high',
        'charge_water_orb',
        'enchant_jewelry_diamond',
        'fire_blast',
        'charge_earth_orb',
        'wind_wave',
        'charge_fire_orb',
        'water_wave',
        'charge_air_orb',
        'enchant_jewelry_dragonstone',
        'earth_wave',
        'fire_wave',
        'iban_blast',
        'teleport_ardougne',
        'teleport_watchtower',
        'vulnerability',
        'enfeeble',
        'stun',
        'flames_of_zamorak',
        'claws_of_guthix',
        'saradomin_strike',
        'call_animal',
        'raise_undead',
        'summon_demon'
    ],

    magicon2: [
        'bind',
        'snare',
        'entangle',
        'charge'
    ],

    mapdots: [
        'item',
        'npc',
        'player',
        'friend'
    ],

    mapfunction: [
        'general_store',
        'sword_shop',
        'magic_shop',
        'axe_shop',
        'helmet_shop',
        'bank',
        'quest_start',
        'amulet_shop',
        'mining_site',
        'furnace',
        'anvil',
        'combat_training',
        'dungeon',
        'staff_shop',
        'platebody_shop',
        'platelegs_shop',
        'scimitar_shop',
        'archery_shop',
        'shield_shop',
        'altar',
        'herbalist',
        'jewelry',
        'gem_shop',
        'crafting_shop',
        'candle_shop',
        'fishing_shop',
        'fishing_spot',
        'clothes_shop',
        'apothecary',
        'silk_trader',
        'kebab_seller',
        'bar',
        'mace_shop',
        'tannery',
        'rare_trees',
        'spinning_wheel',
        'food_shop',
        'cookery_shop',
        'blank',
        'water_source',
        'cooking_range',
        'skirt_shop',
        'potters_wheel',
        'windmill',
        'mining_shop',
        'chainmail_shop',
        'silver_shop',
        'fur_trader',
        'spice_shop'
    ],

    mapscene: [
        'tree1',
        'tree2',
        'tree3',
        'tree4',
        'cactus',
        'tree5',
        'dead_tree',
        'ladder',
        'fountain',
        'bush',
        'tree6',
        'rock1',
        'rock2',
        'wooden_log',
        'henge',
        'fire_wall',
        'glider_top_left',
        'glider_top_right',
        'glider_bottom_left',
        'glider_bottom_right',
        'boat_center',
        'basalt_rock',
        'riverbank',
        'tropical_tree',
        'rock3',
        'rock4',
        'boat2',
        'boat1',
        'boat_vertical',
        'boat3',
        'boat5',
        'boat4',
        'boat7',
        'boat6',
        'boat8',
        'boat9',
        'boat11',
        'boat10',
        'boat13',
        'boat12',
        'boat14',
        'boat15',
        'boat_horizontal',
        'trapdoor',
        'water',
        'pink',
        'wooden_dock',
        'tree_support',
        'desert',
        'sand'
    ],

    miscgraphics: [
        'inactive',
        'frame',
        'vertical',
        'horizontal',
        'left',
        'right_compare',
        'right',
        'left_active',
        'right_active',
        'active',
        'unchecked',
        'checked'
    ],

    miscgraphics2: [
        'inactive',
        'active'
    ],

    miscgraphics3: [
        'inactive',
        'active'
    ],

    prayeroff: [
        'thick_skin',
        'burst_of_strength',
        'clarity_of_thought',
        'rock_skin',
        'superhuman_strength',
        'improved_reflexes',
        'rapid_restore',
        'rapid_heal',
        'protect_items',
        'steel_skin',
        'ultimate_strength',
        'incredible_reflexes',
        'protect_from_magic',
        'protect_from_missiles',
        'protect_from_melee'
    ],

    prayeron: [
        'thick_skin',
        'burst_of_strength',
        'clarity_of_thought',
        'rock_skin',
        'superhuman_strength',
        'improved_reflexes',
        'rapid_restore',
        'rapid_heal',
        'protect_items',
        'steel_skin',
        'ultimate_strength',
        'incredible_reflexes',
        'protect_from_magic',
        'protect_from_missiles',
        'protect_from_melee'
    ],

    scrollbar: [
        'up',
        'down'
    ],

    sideicons: [
        'combat',
        'skills',
        'quests',
        'inventory',
        'equipment',
        'prayer',
        'magic',
        'friends_list',
        'ignore_list',
        'logout',
        'game_options',
        'player_controls',
        'music_player'
    ],

    staticons: [
        'attack',
        'strength',
        'defence',
        'ranged',
        'prayer',
        'magic',
        'hitpoints',
        'agility',
        'herblore',
        'thieving',
        'crafting',
        'fletching',
        'mining',
        'smithing',
        'fishing',
        'cooking',
        'firemaking',
        'woodcutting'
    ],

    staticons2: [
        'runecrafting'
    ],

    steelborder: [
        'top_left',
        'top_right',
        'bottom_left',
        'bottom_right'
    ],

    steelborder2: [
        'top',
        'side'
    ],

    sworddecor: [
        'active_right',
        'active_left',
        'inactive_left',
        'inactive_right'
    ],

    wornicons: [
        'helmet',
        'cape',
        'amulet',
        'main_hand',
        'ring',
        'chest',
        'off_hand',
        'legs',
        'gloves',
        'boots',
        'ammo'
    ]
};
