enum HuntMode {
    NONE,
    RANGED,
    CONSTANT_MELEE,
    CONSTANT_RANGED,
    COWARDLY,
    NOTBUSY_MELEE,
    NOTBUSY_RANGE,
    AGGRESSIVE_MELEE,
    AGGRESSIVE_MELEE_EXTRA,
    AGGRESSIVE_RANGED,
    AGGRESSIVE_RANGED_EXTRA,
    AP1_TRIGGER_CONSTANT,
    AP1_TRIGGER,
    AP2_TRIGGER_CONSTANT,
    AP2_TRIGGER,
    OP1_TRIGGER_CONSTANT,
    OP1_TRIGGER,
    OP2_TRIGGER_CONSTANT,
    OP2_TRIGGER,
    QUEUE11_TRIGGER_CONSTANT,
    QUEUE11_TRIGGER,
    BIGMONSTER_MELEE,
    BIGMONSTER_RANGED
}

export default HuntMode;
