import ClientProtBase from '#/network/game/client/codec/ClientProtBase.js';

export default class ClientProt244 extends ClientProtBase {
    static all: ClientProt244[] = [];
    static byId: ClientProt244[] = [];

    static readonly NO_TIMEOUT = new ClientProt244(6, 107, 0); // NXT naming

    static readonly IDLE_TIMER = new ClientProt244(30, 146, 0);

    static readonly EVENT_TRACKING = new ClientProt244(34, 217, -2);

    // autogenerated as part of obfuscation process
    static readonly ANTICHEAT_OPLOGIC1 = new ClientProt244(60, 47, 4);
    static readonly ANTICHEAT_OPLOGIC2 = new ClientProt244(61, 218, 4);
    static readonly ANTICHEAT_OPLOGIC3 = new ClientProt244(62, 37, 3);
    static readonly ANTICHEAT_OPLOGIC4 = new ClientProt244(63, 34, 2);
    static readonly ANTICHEAT_OPLOGIC5 = new ClientProt244(64, 7, 0);
    static readonly ANTICHEAT_OPLOGIC6 = new ClientProt244(65, 177, 4);
    static readonly ANTICHEAT_OPLOGIC7 = new ClientProt244(66, 50, 4);
    static readonly ANTICHEAT_OPLOGIC8 = new ClientProt244(67, 100, 2);
    static readonly ANTICHEAT_OPLOGIC9 = new ClientProt244(68, 169, 1);

    // autogenerated as part of obfuscation process
    static readonly ANTICHEAT_CYCLELOGIC1 = new ClientProt244(70, 46, 1);
    static readonly ANTICHEAT_CYCLELOGIC2 = new ClientProt244(71, 148, -1);
    static readonly ANTICHEAT_CYCLELOGIC3 = new ClientProt244(74, 144, 3);
    static readonly ANTICHEAT_CYCLELOGIC4 = new ClientProt244(72, 41, 4);
    static readonly ANTICHEAT_CYCLELOGIC5 = new ClientProt244(75, 232, 0);
    static readonly ANTICHEAT_CYCLELOGIC6 = new ClientProt244(73, 215, -1);

    static readonly OPOBJ1 = new ClientProt244(80, 231, 6); // NXT naming
    static readonly OPOBJ2 = new ClientProt244(81, 110, 6); // NXT naming
    static readonly OPOBJ3 = new ClientProt244(82, 27, 6); // NXT naming
    static readonly OPOBJ4 = new ClientProt244(83, 17, 6); // NXT naming
    static readonly OPOBJ5 = new ClientProt244(84, 225, 6); // NXT naming
    static readonly OPOBJT = new ClientProt244(88, 25, 8); // NXT naming
    static readonly OPOBJU = new ClientProt244(89, 111, 12); // NXT naming

    static readonly OPNPC1 = new ClientProt244(100, 222, 2); // NXT naming
    static readonly OPNPC2 = new ClientProt244(101, 84, 2); // NXT naming
    static readonly OPNPC3 = new ClientProt244(102, 132, 2); // NXT naming
    static readonly OPNPC4 = new ClientProt244(103, 229, 2); // NXT naming
    static readonly OPNPC5 = new ClientProt244(104, 102, 2); // NXT naming
    static readonly OPNPCT = new ClientProt244(108, 101, 4); // NXT naming
    static readonly OPNPCU = new ClientProt244(109, 52, 8); // NXT naming

    static readonly OPLOC1 = new ClientProt244(120, 238, 6); // NXT naming
    static readonly OPLOC2 = new ClientProt244(121, 38, 6); // NXT naming
    static readonly OPLOC3 = new ClientProt244(122, 19, 6); // NXT naming
    static readonly OPLOC4 = new ClientProt244(123, 55, 6); // NXT naming
    static readonly OPLOC5 = new ClientProt244(124, 243, 6); // NXT naming
    static readonly OPLOCT = new ClientProt244(128, 182, 8); // NXT naming
    static readonly OPLOCU = new ClientProt244(129, 106, 12); // NXT naming

    static readonly OPPLAYER1 = new ClientProt244(140, 211, 2); // NXT naming
    static readonly OPPLAYER2 = new ClientProt244(141, 219, 2); // NXT naming
    static readonly OPPLAYER3 = new ClientProt244(142, 64, 2); // NXT naming
    static readonly OPPLAYER4 = new ClientProt244(143, 43, 2); // NXT naming
    static readonly OPPLAYERT = new ClientProt244(148, 73, 4); // NXT naming
    static readonly OPPLAYERU = new ClientProt244(149, 48, 8); // NXT naming

    static readonly OPHELD1 = new ClientProt244(160, 228, 6); // name based on runescript trigger
    static readonly OPHELD2 = new ClientProt244(161, 166, 6); // name based on runescript trigger
    static readonly OPHELD3 = new ClientProt244(162, 221, 6); // name based on runescript trigger
    static readonly OPHELD4 = new ClientProt244(163, 6, 6); // name based on runescript trigger
    static readonly OPHELD5 = new ClientProt244(164, 133, 6); // name based on runescript trigger
    static readonly OPHELDT = new ClientProt244(168, 142, 8); // name based on runescript trigger
    static readonly OPHELDU = new ClientProt244(169, 58, 12); // name based on runescript trigger

    static readonly INV_BUTTON1 = new ClientProt244(190, 153, 6); // NXT has "IF_BUTTON1" but for our interface system, this makes more sense
    static readonly INV_BUTTON2 = new ClientProt244(191, 193, 6); // NXT has "IF_BUTTON2" but for our interface system, this makes more sense
    static readonly INV_BUTTON3 = new ClientProt244(192, 158, 6); // NXT has "IF_BUTTON3" but for our interface system, this makes more sense
    static readonly INV_BUTTON4 = new ClientProt244(193, 204, 6); // NXT has "IF_BUTTON4" but for our interface system, this makes more sense
    static readonly INV_BUTTON5 = new ClientProt244(194, 212, 6); // NXT has "IF_BUTTON5" but for our interface system, this makes more sense
    static readonly IF_BUTTON = new ClientProt244(200, 39, 2); // NXT naming

    static readonly RESUME_PAUSEBUTTON = new ClientProt244(201, 11, 2); // NXT naming
    static readonly CLOSE_MODAL = new ClientProt244(202, 187, 0); // NXT naming
    static readonly RESUME_P_COUNTDIALOG = new ClientProt244(203, 190, 4); // NXT naming
    static readonly TUTORIAL_CLICKSIDE = new ClientProt244(204, 233, 1);

    static readonly MOVE_OPCLICK = new ClientProt244(242, 167, -1); // comes with OP packets, name based on other MOVE packets
    static readonly REPORT_ABUSE = new ClientProt244(243, 251, 10);
    static readonly MOVE_MINIMAPCLICK = new ClientProt244(244, 56, -1); // NXT naming
    static readonly INV_BUTTOND = new ClientProt244(245, 81, 6); // NXT has "IF_BUTTOND" but for our interface system, this makes more sense
    static readonly IGNORELIST_DEL = new ClientProt244(246, 207, 8); // NXT naming
    static readonly IGNORELIST_ADD = new ClientProt244(247, 203, 8); // NXT naming
    static readonly IF_PLAYERDESIGN = new ClientProt244(248, 8, 13);
    static readonly CHAT_SETMODE = new ClientProt244(249, 98, 3); // NXT naming
    static readonly MESSAGE_PRIVATE = new ClientProt244(250, 170, -1); // NXT naming
    static readonly FRIENDLIST_DEL = new ClientProt244(251, 69, 8); // NXT naming
    static readonly FRIENDLIST_ADD = new ClientProt244(252, 9, 8); // NXT naming
    static readonly CLIENT_CHEAT = new ClientProt244(253, 76, -1); // NXT naming
    static readonly MESSAGE_PUBLIC = new ClientProt244(254, 171, -1); // NXT naming
    static readonly MOVE_GAMECLICK = new ClientProt244(255, 63, -1); // NXT naming

    // in these old revisions we can actually get the packet index from a leftover array in the client source
    constructor(
        readonly index: number,
        readonly id: number,
        readonly length: number
    ) {
        super(index, id, length);

        ClientProt244.all[index] = this;
        ClientProt244.byId[id] = this;
    }
}
