import ClientProtRepository from '#/network/game/client/codec/ClientProtRepository.js';
import ChatSetModeDecoder from '#/network/game/client/codec/rs244/ChatSetModeDecoder.js';
import ClientCheatDecoder from '#/network/game/client/codec/rs244/ClientCheatDecoder.js';
import ClientProt244 from '#/network/game/client/codec/rs244/ClientProt244.js';
import CloseModalDecoder from '#/network/game/client/codec/rs244/CloseModalDecoder.js';
import EventTrackingDecoder from '#/network/game/client/codec/rs244/EventTrackingDecoder.js';
import FriendListAddDecoder from '#/network/game/client/codec/rs244/FriendListAddDecoder.js';
import FriendListDelDecoder from '#/network/game/client/codec/rs244/FriendListDelDecoder.js';
import IdleTimerDecoder from '#/network/game/client/codec/rs244/IdleTimerDecoder.js';
import IfButtonDecoder from '#/network/game/client/codec/rs244/IfButtonDecoder.js';
import IfPlayerDesignDecoder from '#/network/game/client/codec/rs244/IfPlayerDesignDecoder.js';
import IgnoreListAddDecoder from '#/network/game/client/codec/rs244/IgnoreListAddDecoder.js';
import IgnoreListDelDecoder from '#/network/game/client/codec/rs244/IgnoreListDelDecoder.js';
import InvButtonDDecoder from '#/network/game/client/codec/rs244/InvButtonDDecoder.js';
import InvButtonDecoder from '#/network/game/client/codec/rs244/InvButtonDecoder.js';
import MessagePrivateDecoder from '#/network/game/client/codec/rs244/MessagePrivateDecoder.js';
import MessagePublicDecoder from '#/network/game/client/codec/rs244/MessagePublicDecoder.js';
import MoveClickDecoder from '#/network/game/client/codec/rs244/MoveClickDecoder.js';
import OpHeldDecoder from '#/network/game/client/codec/rs244/OpHeldDecoder.js';
import OpHeldTDecoder from '#/network/game/client/codec/rs244/OpHeldTDecoder.js';
import OpHeldUDecoder from '#/network/game/client/codec/rs244/OpHeldUDecoder.js';
import OpLocDecoder from '#/network/game/client/codec/rs244/OpLocDecoder.js';
import OpLocTDecoder from '#/network/game/client/codec/rs244/OpLocTDecoder.js';
import OpLocUDecoder from '#/network/game/client/codec/rs244/OpLocUDecoder.js';
import OpNpcDecoder from '#/network/game/client/codec/rs244/OpNpcDecoder.js';
import OpNpcTDecoder from '#/network/game/client/codec/rs244/OpNpcTDecoder.js';
import OpNpcUDecoder from '#/network/game/client/codec/rs244/OpNpcUDecoder.js';
import OpObjDecoder from '#/network/game/client/codec/rs244/OpObjDecoder.js';
import OpObjTDecoder from '#/network/game/client/codec/rs244/OpObjTDecoder.js';
import OpObjUDecoder from '#/network/game/client/codec/rs244/OpObjUDecoder.js';
import OpPlayerDecoder from '#/network/game/client/codec/rs244/OpPlayerDecoder.js';
import OpPlayerTDecoder from '#/network/game/client/codec/rs244/OpPlayerTDecoder.js';
import OpPlayerUDecoder from '#/network/game/client/codec/rs244/OpPlayerUDecoder.js';
import ReportAbuseDecoder from '#/network/game/client/codec/rs244/ReportAbuseDecoder.js';
import ResumePauseButtonDecoder from '#/network/game/client/codec/rs244/ResumePauseButtonDecoder.js';
import ResumePCountDialogDecoder from '#/network/game/client/codec/rs244/ResumePCountDialogDecoder.js';
import TutorialClickSideDecoder from '#/network/game/client/codec/rs244/TutorialClickSideDecoder.js';
import ChatSetModeHandler from '#/network/game/client/handler/ChatSetModeHandler.js';
import ClientCheatHandler from '#/network/game/client/handler/ClientCheatHandler.js';
import CloseModalHandler from '#/network/game/client/handler/CloseModalHandler.js';
import EventTrackingHandler from '#/network/game/client/handler/EventTrackingHandler.js';
import FriendListAddHandler from '#/network/game/client/handler/FriendListAddHandler.js';
import FriendListDelHandler from '#/network/game/client/handler/FriendListDelHandler.js';
import IdleTimerHandler from '#/network/game/client/handler/IdleTimerHandler.js';
import IfButtonHandler from '#/network/game/client/handler/IfButtonHandler.js';
import IfPlayerDesignHandler from '#/network/game/client/handler/IfPlayerDesignHandler.js';
import IgnoreListAddHandler from '#/network/game/client/handler/IgnoreListAddHandler.js';
import IgnoreListDelHandler from '#/network/game/client/handler/IgnoreListDelHandler.js';
import InvButtonDHandler from '#/network/game/client/handler/InvButtonDHandler.js';
import InvButtonHandler from '#/network/game/client/handler/InvButtonHandler.js';
import MessagePrivateHandler from '#/network/game/client/handler/MessagePrivateHandler.js';
import MessagePublicHandler from '#/network/game/client/handler/MessagePublicHandler.js';
import MoveClickHandler from '#/network/game/client/handler/MoveClickHandler.js';
import OpHeldHandler from '#/network/game/client/handler/OpHeldHandler.js';
import OpHeldTHandler from '#/network/game/client/handler/OpHeldTHandler.js';
import OpHeldUHandler from '#/network/game/client/handler/OpHeldUHandler.js';
import OpLocHandler from '#/network/game/client/handler/OpLocHandler.js';
import OpLocTHandler from '#/network/game/client/handler/OpLocTHandler.js';
import OpLocUHandler from '#/network/game/client/handler/OpLocUHandler.js';
import OpNpcHandler from '#/network/game/client/handler/OpNpcHandler.js';
import OpNpcTHandler from '#/network/game/client/handler/OpNpcTHandler.js';
import OpNpcUHandler from '#/network/game/client/handler/OpNpcUHandler.js';
import OpObjHandler from '#/network/game/client/handler/OpObjHandler.js';
import OpObjTHandler from '#/network/game/client/handler/OpObjTHandler.js';
import OpObjUHandler from '#/network/game/client/handler/OpObjUHandler.js';
import OpPlayerHandler from '#/network/game/client/handler/OpPlayerHandler.js';
import OpPlayerTHandler from '#/network/game/client/handler/OpPlayerTHandler.js';
import OpPlayerUHandler from '#/network/game/client/handler/OpPlayerUHandler.js';
import ReportAbuseHandler from '#/network/game/client/handler/ReportAbuseHandler.js';
import ResumePauseButtonHandler from '#/network/game/client/handler/ResumePauseButtonHandler.js';
import ResumePCountDialogHandler from '#/network/game/client/handler/ResumePCountDialogHandler.js';
import TutorialClickSideHandler from '#/network/game/client/handler/TutorialClickSideHandler.js';

export default class ClientProtRepository244 extends ClientProtRepository {
    constructor() {
        super();

        this.bind(new ClientCheatDecoder(), new ClientCheatHandler());
        this.bind(new CloseModalDecoder(), new CloseModalHandler());
        this.bind(new FriendListAddDecoder(), new FriendListAddHandler());
        this.bind(new FriendListDelDecoder(), new FriendListDelHandler());
        this.bind(new IdleTimerDecoder(), new IdleTimerHandler());
        this.bind(new IfButtonDecoder(), new IfButtonHandler());
        this.bind(new IfPlayerDesignDecoder(), new IfPlayerDesignHandler());
        this.bind(new IgnoreListAddDecoder(), new IgnoreListAddHandler());
        this.bind(new IgnoreListDelDecoder(), new IgnoreListDelHandler());
        this.bind(new InvButtonDecoder(ClientProt244.INV_BUTTON1, 1), new InvButtonHandler());
        this.bind(new InvButtonDecoder(ClientProt244.INV_BUTTON2, 2), new InvButtonHandler());
        this.bind(new InvButtonDecoder(ClientProt244.INV_BUTTON3, 3), new InvButtonHandler());
        this.bind(new InvButtonDecoder(ClientProt244.INV_BUTTON4, 4), new InvButtonHandler());
        this.bind(new InvButtonDecoder(ClientProt244.INV_BUTTON5, 5), new InvButtonHandler());
        this.bind(new InvButtonDDecoder(), new InvButtonDHandler());
        this.bind(new MessagePrivateDecoder(), new MessagePrivateHandler());
        this.bind(new MessagePublicDecoder(), new MessagePublicHandler());
        this.bind(new MoveClickDecoder(ClientProt244.MOVE_GAMECLICK), new MoveClickHandler());
        this.bind(new MoveClickDecoder(ClientProt244.MOVE_OPCLICK), new MoveClickHandler());
        this.bind(new MoveClickDecoder(ClientProt244.MOVE_MINIMAPCLICK), new MoveClickHandler());
        // this.bind(new NoTimeoutDecoder(), new NoTimeoutHandler());
        this.bind(new OpHeldDecoder(ClientProt244.OPHELD1, 1), new OpHeldHandler());
        this.bind(new OpHeldDecoder(ClientProt244.OPHELD2, 2), new OpHeldHandler());
        this.bind(new OpHeldDecoder(ClientProt244.OPHELD3, 3), new OpHeldHandler());
        this.bind(new OpHeldDecoder(ClientProt244.OPHELD4, 4), new OpHeldHandler());
        this.bind(new OpHeldDecoder(ClientProt244.OPHELD5, 5), new OpHeldHandler());
        this.bind(new OpHeldTDecoder(), new OpHeldTHandler());
        this.bind(new OpHeldUDecoder(), new OpHeldUHandler());
        this.bind(new OpLocDecoder(ClientProt244.OPLOC1, 1), new OpLocHandler());
        this.bind(new OpLocDecoder(ClientProt244.OPLOC2, 2), new OpLocHandler());
        this.bind(new OpLocDecoder(ClientProt244.OPLOC3, 3), new OpLocHandler());
        this.bind(new OpLocDecoder(ClientProt244.OPLOC4, 4), new OpLocHandler());
        this.bind(new OpLocDecoder(ClientProt244.OPLOC5, 5), new OpLocHandler());
        this.bind(new OpLocTDecoder(), new OpLocTHandler());
        this.bind(new OpLocUDecoder(), new OpLocUHandler());
        this.bind(new OpNpcDecoder(ClientProt244.OPNPC1, 1), new OpNpcHandler());
        this.bind(new OpNpcDecoder(ClientProt244.OPNPC2, 2), new OpNpcHandler());
        this.bind(new OpNpcDecoder(ClientProt244.OPNPC3, 3), new OpNpcHandler());
        this.bind(new OpNpcDecoder(ClientProt244.OPNPC4, 4), new OpNpcHandler());
        this.bind(new OpNpcDecoder(ClientProt244.OPNPC5, 5), new OpNpcHandler());
        this.bind(new OpNpcTDecoder(), new OpNpcTHandler());
        this.bind(new OpNpcUDecoder(), new OpNpcUHandler());
        this.bind(new OpObjDecoder(ClientProt244.OPOBJ1, 1), new OpObjHandler());
        this.bind(new OpObjDecoder(ClientProt244.OPOBJ2, 2), new OpObjHandler());
        this.bind(new OpObjDecoder(ClientProt244.OPOBJ3, 3), new OpObjHandler());
        this.bind(new OpObjDecoder(ClientProt244.OPOBJ4, 4), new OpObjHandler());
        this.bind(new OpObjDecoder(ClientProt244.OPOBJ5, 5), new OpObjHandler());
        this.bind(new OpObjTDecoder(), new OpObjTHandler());
        this.bind(new OpObjUDecoder(), new OpObjUHandler());
        this.bind(new OpPlayerDecoder(ClientProt244.OPPLAYER1, 1), new OpPlayerHandler());
        this.bind(new OpPlayerDecoder(ClientProt244.OPPLAYER2, 2), new OpPlayerHandler());
        this.bind(new OpPlayerDecoder(ClientProt244.OPPLAYER3, 3), new OpPlayerHandler());
        this.bind(new OpPlayerDecoder(ClientProt244.OPPLAYER4, 4), new OpPlayerHandler());
        this.bind(new OpPlayerTDecoder(), new OpPlayerTHandler());
        this.bind(new OpPlayerUDecoder(), new OpPlayerUHandler());
        this.bind(new ResumePauseButtonDecoder(), new ResumePauseButtonHandler());
        this.bind(new ResumePCountDialogDecoder(), new ResumePCountDialogHandler());
        this.bind(new TutorialClickSideDecoder(), new TutorialClickSideHandler());
        this.bind(new ChatSetModeDecoder(), new ChatSetModeHandler());
        this.bind(new EventTrackingDecoder(), new EventTrackingHandler());
        this.bind(new ReportAbuseDecoder(), new ReportAbuseHandler());
    }
}
