import CamLookAtEncoder from '#/network/game/server/codec/rs225/CamLookAtEncoder.js';
import CamMoveToEncoder from '#/network/game/server/codec/rs225/CamMoveToEncoder.js';
import CamResetEncoder from '#/network/game/server/codec/rs225/CamResetEncoder.js';
import CamShakeEncoder from '#/network/game/server/codec/rs225/CamShakeEncoder.js';
import ChatFilterSettingsEncoder from '#/network/game/server/codec/rs225/ChatFilterSettingsEncoder.js';
import DataLandDoneEncoder from '#/network/game/server/codec/rs225/DataLandDoneEncoder.js';
import DataLandEncoder from '#/network/game/server/codec/rs225/DataLandEncoder.js';
import DataLocDoneEncoder from '#/network/game/server/codec/rs225/DataLocDoneEncoder.js';
import DataLocEncoder from '#/network/game/server/codec/rs225/DataLocEncoder.js';
import EnableTrackingEncoder from '#/network/game/server/codec/rs225/EnableTrackingEncoder.js';
import FinishTrackingEncoder from '#/network/game/server/codec/rs225/FinishTrackingEncoder.js';
import HintArrowEncoder from '#/network/game/server/codec/rs225/HintArrowEncoder.js';
import IfCloseEncoder from '#/network/game/server/codec/rs225/IfCloseEncoder.js';
import IfOpenChatEncoder from '#/network/game/server/codec/rs225/IfOpenChatEncoder.js';
import IfOpenMainEncoder from '#/network/game/server/codec/rs225/IfOpenMainEncoder.js';
import IfOpenMainSideEncoder from '#/network/game/server/codec/rs225/IfOpenMainSideEncoder.js';
import IfOpenSideEncoder from '#/network/game/server/codec/rs225/IfOpenSideEncoder.js';
import IfSetAnimEncoder from '#/network/game/server/codec/rs225/IfSetAnimEncoder.js';
import IfSetColourEncoder from '#/network/game/server/codec/rs225/IfSetColourEncoder.js';
import IfSetHideEncoder from '#/network/game/server/codec/rs225/IfSetHideEncoder.js';
import IfSetModelEncoder from '#/network/game/server/codec/rs225/IfSetModelEncoder.js';
import IfSetNpcHeadEncoder from '#/network/game/server/codec/rs225/IfSetNpcHeadEncoder.js';
import IfSetObjectEncoder from '#/network/game/server/codec/rs225/IfSetObjectEncoder.js';
import IfSetPlayerHeadEncoder from '#/network/game/server/codec/rs225/IfSetPlayerHeadEncoder.js';
import IfSetPositionEncoder from '#/network/game/server/codec/rs225/IfSetPositionEncoder.js';
import IfSetRecolEncoder from '#/network/game/server/codec/rs225/IfSetRecolEncoder.js';
import IfSetTabActiveEncoder from '#/network/game/server/codec/rs225/IfSetTabActiveEncoder.js';
import IfSetTabEncoder from '#/network/game/server/codec/rs225/IfSetTabEncoder.js';
import IfSetTextEncoder from '#/network/game/server/codec/rs225/IfSetTextEncoder.js';
import LastLoginInfoEncoder from '#/network/game/server/codec/rs225/LastLoginInfoEncoder.js';
import LocAddChangeEncoder from '#/network/game/server/codec/rs225/LocAddChangeEncoder.js';
import LocAnimEncoder from '#/network/game/server/codec/rs225/LocAnimEncoder.js';
import LocDelEncoder from '#/network/game/server/codec/rs225/LocDelEncoder.js';
import LocMergeEncoder from '#/network/game/server/codec/rs225/LocMergeEncoder.js';
import LogoutEncoder from '#/network/game/server/codec/rs225/LogoutEncoder.js';
import MapAnimEncoder from '#/network/game/server/codec/rs225/MapAnimEncoder.js';
import MapProjAnimEncoder from '#/network/game/server/codec/rs225/MapProjAnimEncoder.js';
import MessageGameEncoder from '#/network/game/server/codec/rs225/MessageGameEncoder.js';
import MessagePrivateEncoder from '#/network/game/server/codec/rs225/MessagePrivateEncoder.js';
import MidiJingleEncoder from '#/network/game/server/codec/rs225/MidiJingleEncoder.js';
import MidiSongEncoder from '#/network/game/server/codec/rs225/MidiSongEncoder.js';
import NpcInfoEncoder from '#/network/game/server/codec/rs225/NpcInfoEncoder.js';
import ObjAddEncoder from '#/network/game/server/codec/rs225/ObjAddEncoder.js';
import ObjCountEncoder from '#/network/game/server/codec/rs225/ObjCountEncoder.js';
import ObjDelEncoder from '#/network/game/server/codec/rs225/ObjDelEncoder.js';
import ObjRevealEncoder from '#/network/game/server/codec/rs225/ObjRevealEncoder.js';
import PCountDialogEncoder from '#/network/game/server/codec/rs225/PCountDialogEncoder.js';
import PlayerInfoEncoder from '#/network/game/server/codec/rs225/PlayerInfoEncoder.js';
import RebuildNormalEncoder from '#/network/game/server/codec/rs225/RebuildNormalEncoder.js';
import ResetAnimsEncoder from '#/network/game/server/codec/rs225/ResetAnimsEncoder.js';
import ResetClientVarCacheEncoder from '#/network/game/server/codec/rs225/ResetClientVarCacheEncoder.js';
import SetMultiwayEncoder from '#/network/game/server/codec/rs225/SetMultiwayEncoder.js';
import SynthSoundEncoder from '#/network/game/server/codec/rs225/SynthSoundEncoder.js';
import TutFlashEncoder from '#/network/game/server/codec/rs225/TutFlashEncoder.js';
import TutOpenEncoder from '#/network/game/server/codec/rs225/TutOpenEncoder.js';
import UnsetMapFlagEncoder from '#/network/game/server/codec/rs225/UnsetMapFlagEncoder.js';
import UpdateFriendListEncoder from '#/network/game/server/codec/rs225/UpdateFriendListEncoder.js';
import UpdateIgnoreListEncoder from '#/network/game/server/codec/rs225/UpdateIgnoreListEncoder.js';
import UpdateInvFullEncoder from '#/network/game/server/codec/rs225/UpdateInvFullEncoder.js';
import UpdateInvPartialEncoder from '#/network/game/server/codec/rs225/UpdateInvPartialEncoder.js';
import UpdateInvStopTransmitEncoder from '#/network/game/server/codec/rs225/UpdateInvStopTransmitEncoder.js';
import UpdatePidEncoder from '#/network/game/server/codec/rs225/UpdatePidEncoder.js';
import UpdateRebootTimerEncoder from '#/network/game/server/codec/rs225/UpdateRebootTimerEncoder.js';
import UpdateRunEnergyEncoder from '#/network/game/server/codec/rs225/UpdateRunEnergyEncoder.js';
import UpdateRunWeightEncoder from '#/network/game/server/codec/rs225/UpdateRunWeightEncoder.js';
import UpdateStatEncoder from '#/network/game/server/codec/rs225/UpdateStatEncoder.js';
import UpdateZoneFullFollowsEncoder from '#/network/game/server/codec/rs225/UpdateZoneFullFollowsEncoder.js';
import UpdateZonePartialEnclosedEncoder from '#/network/game/server/codec/rs225/UpdateZonePartialEnclosedEncoder.js';
import UpdateZonePartialFollowsEncoder from '#/network/game/server/codec/rs225/UpdateZonePartialFollowsEncoder.js';
import VarpLargeEncoder from '#/network/game/server/codec/rs225/VarpLargeEncoder.js';
import VarpSmallEncoder from '#/network/game/server/codec/rs225/VarpSmallEncoder.js';
import ServerProtRepository from '#/network/game/server/codec/ServerProtRepository.js';
import CamLookAt from '#/network/game/server/model/CamLookAt.js';
import CamMoveTo from '#/network/game/server/model/CamMoveTo.js';
import CamReset from '#/network/game/server/model/CamReset.js';
import CamShake from '#/network/game/server/model/CamShake.js';
import ChatFilterSettings from '#/network/game/server/model/ChatFilterSettings.js';
import DataLand from '#/network/game/server/model/DataLand.js';
import DataLandDone from '#/network/game/server/model/DataLandDone.js';
import DataLoc from '#/network/game/server/model/DataLoc.js';
import DataLocDone from '#/network/game/server/model/DataLocDone.js';
import EnableTracking from '#/network/game/server/model/EnableTracking.js';
import FinishTracking from '#/network/game/server/model/FinishTracking.js';
import HintArrow from '#/network/game/server/model/HintArrow.js';
import IfClose from '#/network/game/server/model/IfClose.js';
import IfOpenChat from '#/network/game/server/model/IfOpenChat.js';
import IfOpenMain from '#/network/game/server/model/IfOpenMain.js';
import IfOpenMainSide from '#/network/game/server/model/IfOpenMainSide.js';
import IfOpenSide from '#/network/game/server/model/IfOpenSide.js';
import IfSetAnim from '#/network/game/server/model/IfSetAnim.js';
import IfSetColour from '#/network/game/server/model/IfSetColour.js';
import IfSetHide from '#/network/game/server/model/IfSetHide.js';
import IfSetModel from '#/network/game/server/model/IfSetModel.js';
import IfSetNpcHead from '#/network/game/server/model/IfSetNpcHead.js';
import IfSetObject from '#/network/game/server/model/IfSetObject.js';
import IfSetPlayerHead from '#/network/game/server/model/IfSetPlayerHead.js';
import IfSetPosition from '#/network/game/server/model/IfSetPosition.js';
import IfSetRecol from '#/network/game/server/model/IfSetRecol.js';
import IfSetTab from '#/network/game/server/model/IfSetTab.js';
import IfSetTabActive from '#/network/game/server/model/IfSetTabActive.js';
import IfSetText from '#/network/game/server/model/IfSetText.js';
import LastLoginInfo from '#/network/game/server/model/LastLoginInfo.js';
import LocAddChange from '#/network/game/server/model/LocAddChange.js';
import LocAnim from '#/network/game/server/model/LocAnim.js';
import LocDel from '#/network/game/server/model/LocDel.js';
import LocMerge from '#/network/game/server/model/LocMerge.js';
import Logout from '#/network/game/server/model/Logout.js';
import MapAnim from '#/network/game/server/model/MapAnim.js';
import MapProjAnim from '#/network/game/server/model/MapProjAnim.js';
import MessageGame from '#/network/game/server/model/MessageGame.js';
import MessagePrivate from '#/network/game/server/model/MessagePrivate.js';
import MidiJingle from '#/network/game/server/model/MidiJingle.js';
import MidiSong from '#/network/game/server/model/MidiSong.js';
import NpcInfo from '#/network/game/server/model/NpcInfo.js';
import ObjAdd from '#/network/game/server/model/ObjAdd.js';
import ObjCount from '#/network/game/server/model/ObjCount.js';
import ObjDel from '#/network/game/server/model/ObjDel.js';
import ObjReveal from '#/network/game/server/model/ObjReveal.js';
import PCountDialog from '#/network/game/server/model/PCountDialog.js';
import PlayerInfo from '#/network/game/server/model/PlayerInfo.js';
import RebuildNormal from '#/network/game/server/model/RebuildNormal.js';
import ResetAnims from '#/network/game/server/model/ResetAnims.js';
import ResetClientVarCache from '#/network/game/server/model/ResetClientVarCache.js';
import SetMultiway from '#/network/game/server/model/SetMultiway.js';
import SynthSound from '#/network/game/server/model/SynthSound.js';
import TutFlash from '#/network/game/server/model/TutFlash.js';
import TutOpen from '#/network/game/server/model/TutOpen.js';
import UnsetMapFlag from '#/network/game/server/model/UnsetMapFlag.js';
import UpdateFriendList from '#/network/game/server/model/UpdateFriendList.js';
import UpdateIgnoreList from '#/network/game/server/model/UpdateIgnoreList.js';
import UpdateInvFull from '#/network/game/server/model/UpdateInvFull.js';
import UpdateInvPartial from '#/network/game/server/model/UpdateInvPartial.js';
import UpdateInvStopTransmit from '#/network/game/server/model/UpdateInvStopTransmit.js';
import UpdateUid192 from '#/network/game/server/model/UpdatePid.js';
import UpdateRebootTimer from '#/network/game/server/model/UpdateRebootTimer.js';
import UpdateRunEnergy from '#/network/game/server/model/UpdateRunEnergy.js';
import UpdateRunWeight from '#/network/game/server/model/UpdateRunWeight.js';
import UpdateStat from '#/network/game/server/model/UpdateStat.js';
import UpdateZoneFullFollows from '#/network/game/server/model/UpdateZoneFullFollows.js';
import UpdateZonePartialEnclosed from '#/network/game/server/model/UpdateZonePartialEnclosed.js';
import UpdateZonePartialFollows from '#/network/game/server/model/UpdateZonePartialFollows.js';
import VarpLarge from '#/network/game/server/model/VarpLarge.js';
import VarpSmall from '#/network/game/server/model/VarpSmall.js';

export default class ServerProtRepository225 extends ServerProtRepository {
    constructor() {
        super();

        this.bind(CamLookAt, new CamLookAtEncoder());
        this.bind(CamMoveTo, new CamMoveToEncoder());
        this.bind(CamReset, new CamResetEncoder());
        this.bind(CamShake, new CamShakeEncoder());
        this.bind(ChatFilterSettings, new ChatFilterSettingsEncoder());
        this.bind(DataLand, new DataLandEncoder());
        this.bind(DataLandDone, new DataLandDoneEncoder());
        this.bind(DataLoc, new DataLocEncoder());
        this.bind(DataLocDone, new DataLocDoneEncoder());
        this.bind(EnableTracking, new EnableTrackingEncoder());
        this.bind(FinishTracking, new FinishTrackingEncoder());
        this.bind(HintArrow, new HintArrowEncoder());
        this.bind(IfClose, new IfCloseEncoder());
        this.bind(IfOpenChat, new IfOpenChatEncoder());
        this.bind(IfOpenMain, new IfOpenMainEncoder());
        this.bind(IfOpenMainSide, new IfOpenMainSideEncoder());
        this.bind(IfOpenSide, new IfOpenSideEncoder());
        this.bind(IfSetTab, new IfSetTabEncoder());
        this.bind(IfSetAnim, new IfSetAnimEncoder());
        this.bind(IfSetColour, new IfSetColourEncoder());
        this.bind(IfSetHide, new IfSetHideEncoder());
        this.bind(IfSetModel, new IfSetModelEncoder());
        this.bind(IfSetNpcHead, new IfSetNpcHeadEncoder());
        this.bind(IfSetObject, new IfSetObjectEncoder());
        this.bind(IfSetPlayerHead, new IfSetPlayerHeadEncoder());
        this.bind(IfSetPosition, new IfSetPositionEncoder());
        this.bind(IfSetRecol, new IfSetRecolEncoder());
        this.bind(IfSetText, new IfSetTextEncoder());
        this.bind(IfSetTabActive, new IfSetTabActiveEncoder());
        this.bind(LastLoginInfo, new LastLoginInfoEncoder());
        this.bind(LocAddChange, new LocAddChangeEncoder());
        this.bind(LocAnim, new LocAnimEncoder());
        this.bind(LocDel, new LocDelEncoder());
        this.bind(LocMerge, new LocMergeEncoder());
        this.bind(Logout, new LogoutEncoder());
        this.bind(MapAnim, new MapAnimEncoder());
        this.bind(MapProjAnim, new MapProjAnimEncoder());
        this.bind(MessageGame, new MessageGameEncoder());
        this.bind(MessagePrivate, new MessagePrivateEncoder());
        this.bind(MidiJingle, new MidiJingleEncoder());
        this.bind(MidiSong, new MidiSongEncoder());
        this.bind(NpcInfo, new NpcInfoEncoder());
        this.bind(ObjAdd, new ObjAddEncoder());
        this.bind(ObjCount, new ObjCountEncoder());
        this.bind(ObjDel, new ObjDelEncoder());
        this.bind(ObjReveal, new ObjRevealEncoder());
        this.bind(PCountDialog, new PCountDialogEncoder());
        this.bind(PlayerInfo, new PlayerInfoEncoder());
        this.bind(RebuildNormal, new RebuildNormalEncoder());
        this.bind(ResetAnims, new ResetAnimsEncoder());
        this.bind(ResetClientVarCache, new ResetClientVarCacheEncoder());
        this.bind(SetMultiway, new SetMultiwayEncoder());
        this.bind(SynthSound, new SynthSoundEncoder());
        this.bind(TutFlash, new TutFlashEncoder());
        this.bind(TutOpen, new TutOpenEncoder());
        this.bind(UnsetMapFlag, new UnsetMapFlagEncoder());
        this.bind(UpdateFriendList, new UpdateFriendListEncoder());
        this.bind(UpdateIgnoreList, new UpdateIgnoreListEncoder());
        this.bind(UpdateInvFull, new UpdateInvFullEncoder());
        this.bind(UpdateInvPartial, new UpdateInvPartialEncoder());
        this.bind(UpdateInvStopTransmit, new UpdateInvStopTransmitEncoder());
        this.bind(UpdateRunEnergy, new UpdateRunEnergyEncoder());
        this.bind(UpdateRunWeight, new UpdateRunWeightEncoder());
        this.bind(UpdateRebootTimer, new UpdateRebootTimerEncoder());
        this.bind(UpdateStat, new UpdateStatEncoder());
        this.bind(UpdateUid192, new UpdatePidEncoder());
        this.bind(UpdateZoneFullFollows, new UpdateZoneFullFollowsEncoder());
        this.bind(UpdateZonePartialEnclosed, new UpdateZonePartialEnclosedEncoder());
        this.bind(UpdateZonePartialFollows, new UpdateZonePartialFollowsEncoder());
        this.bind(VarpLarge, new VarpLargeEncoder());
        this.bind(VarpSmall, new VarpSmallEncoder());
    }
}
