import CamLookAtEncoder from '#/network/rs225/server/codec/CamLookAtEncoder.js';
import CamMoveToEncoder from '#/network/rs225/server/codec/CamMoveToEncoder.js';
import CamResetEncoder from '#/network/rs225/server/codec/CamResetEncoder.js';
import CamShakeEncoder from '#/network/rs225/server/codec/CamShakeEncoder.js';
import ChatFilterSettingsEncoder from '#/network/rs225/server/codec/ChatFilterSettingsEncoder.js';
import DataLandDoneEncoder from '#/network/rs225/server/codec/DataLandDoneEncoder.js';
import DataLandEncoder from '#/network/rs225/server/codec/DataLandEncoder.js';
import DataLocDoneEncoder from '#/network/rs225/server/codec/DataLocDoneEncoder.js';
import DataLocEncoder from '#/network/rs225/server/codec/DataLocEncoder.js';
import EnableTrackingEncoder from '#/network/rs225/server/codec/EnableTrackingEncoder.js';
import FinishTrackingEncoder from '#/network/rs225/server/codec/FinishTrackingEncoder.js';
import HintArrowEncoder from '#/network/rs225/server/codec/HintArrowEncoder.js';
import IfCloseEncoder from '#/network/rs225/server/codec/IfCloseEncoder.js';
import IfOpenChatEncoder from '#/network/rs225/server/codec/IfOpenChatEncoder.js';
import IfOpenMainEncoder from '#/network/rs225/server/codec/IfOpenMainEncoder.js';
import IfOpenMainSideEncoder from '#/network/rs225/server/codec/IfOpenMainSideEncoder.js';
import IfOpenSideEncoder from '#/network/rs225/server/codec/IfOpenSideEncoder.js';
import IfSetAnimEncoder from '#/network/rs225/server/codec/IfSetAnimEncoder.js';
import IfSetColourEncoder from '#/network/rs225/server/codec/IfSetColourEncoder.js';
import IfSetHideEncoder from '#/network/rs225/server/codec/IfSetHideEncoder.js';
import IfSetModelEncoder from '#/network/rs225/server/codec/IfSetModelEncoder.js';
import IfSetNpcHeadEncoder from '#/network/rs225/server/codec/IfSetNpcHeadEncoder.js';
import IfSetObjectEncoder from '#/network/rs225/server/codec/IfSetObjectEncoder.js';
import IfSetPlayerHeadEncoder from '#/network/rs225/server/codec/IfSetPlayerHeadEncoder.js';
import IfSetPositionEncoder from '#/network/rs225/server/codec/IfSetPositionEncoder.js';
import IfSetRecolEncoder from '#/network/rs225/server/codec/IfSetRecolEncoder.js';
import IfSetTabActiveEncoder from '#/network/rs225/server/codec/IfSetTabActiveEncoder.js';
import IfSetTabEncoder from '#/network/rs225/server/codec/IfSetTabEncoder.js';
import IfSetTextEncoder from '#/network/rs225/server/codec/IfSetTextEncoder.js';
import LastLoginInfoEncoder from '#/network/rs225/server/codec/LastLoginInfoEncoder.js';
import LocAddChangeEncoder from '#/network/rs225/server/codec/LocAddChangeEncoder.js';
import LocAnimEncoder from '#/network/rs225/server/codec/LocAnimEncoder.js';
import LocDelEncoder from '#/network/rs225/server/codec/LocDelEncoder.js';
import LocMergeEncoder from '#/network/rs225/server/codec/LocMergeEncoder.js';
import LogoutEncoder from '#/network/rs225/server/codec/LogoutEncoder.js';
import MapAnimEncoder from '#/network/rs225/server/codec/MapAnimEncoder.js';
import MapProjAnimEncoder from '#/network/rs225/server/codec/MapProjAnimEncoder.js';
import MessageGameEncoder from '#/network/rs225/server/codec/MessageGameEncoder.js';
import MessagePrivateEncoder from '#/network/rs225/server/codec/MessagePrivateEncoder.js';
import MidiJingleEncoder from '#/network/rs225/server/codec/MidiJingleEncoder.js';
import MidiSongEncoder from '#/network/rs225/server/codec/MidiSongEncoder.js';
import NpcInfoAnimEncoder from '#/network/rs225/server/codec/NpcInfoAnimEncoder.js';
import NpcInfoChangeTypeEncoder from '#/network/rs225/server/codec/NpcInfoChangeTypeEncoder.js';
import NpcInfoDamageEncoder from '#/network/rs225/server/codec/NpcInfoDamageEncoder.js';
import NpcInfoEncoder from '#/network/rs225/server/codec/NpcInfoEncoder.js';
import NpcInfoFaceCoordEncoder from '#/network/rs225/server/codec/NpcInfoFaceCoordEncoder.js';
import NpcInfoFaceEntityEncoder from '#/network/rs225/server/codec/NpcInfoFaceEntityEncoder.js';
import NpcInfoSayEncoder from '#/network/rs225/server/codec/NpcInfoSayEncoder.js';
import NpcInfoSpotanimEncoder from '#/network/rs225/server/codec/NpcInfoSpotanimEncoder.js';
import ObjAddEncoder from '#/network/rs225/server/codec/ObjAddEncoder.js';
import ObjCountEncoder from '#/network/rs225/server/codec/ObjCountEncoder.js';
import ObjDelEncoder from '#/network/rs225/server/codec/ObjDelEncoder.js';
import ObjRevealEncoder from '#/network/rs225/server/codec/ObjRevealEncoder.js';
import PCountDialogEncoder from '#/network/rs225/server/codec/PCountDialogEncoder.js';
import PlayerInfoAnimEncoder from '#/network/rs225/server/codec/PlayerInfoAnimEncoder.js';
import PlayerInfoAppearanceEncoder from '#/network/rs225/server/codec/PlayerInfoAppearanceEncoder.js';
import PlayerInfoChatEncoder from '#/network/rs225/server/codec/PlayerInfoChatEncoder.js';
import PlayerInfoDamageEncoder from '#/network/rs225/server/codec/PlayerInfoDamageEncoder.js';
import PlayerInfoEncoder from '#/network/rs225/server/codec/PlayerInfoEncoder.js';
import PlayerInfoExactMoveEncoder from '#/network/rs225/server/codec/PlayerInfoExactMoveEncoder.js';
import PlayerInfoFaceCoordEncoder from '#/network/rs225/server/codec/PlayerInfoFaceCoordEncoder.js';
import PlayerInfoFaceEntityEncoder from '#/network/rs225/server/codec/PlayerInfoFaceEntityEncoder.js';
import PlayerInfoSayEncoder from '#/network/rs225/server/codec/PlayerInfoSayEncoder.js';
import PlayerInfoSpotanimEncoder from '#/network/rs225/server/codec/PlayerInfoSpotanimEncoder.js';
import RebuildNormalEncoder from '#/network/rs225/server/codec/RebuildNormalEncoder.js';
import ResetAnimsEncoder from '#/network/rs225/server/codec/ResetAnimsEncoder.js';
import ResetClientVarCacheEncoder from '#/network/rs225/server/codec/ResetClientVarCacheEncoder.js';
import SetMultiwayEncoder from '#/network/rs225/server/codec/SetMultiwayEncoder.js';
import SynthSoundEncoder from '#/network/rs225/server/codec/SynthSoundEncoder.js';
import TutFlashEncoder from '#/network/rs225/server/codec/TutFlashEncoder.js';
import TutOpenEncoder from '#/network/rs225/server/codec/TutOpenEncoder.js';
import UnsetMapFlagEncoder from '#/network/rs225/server/codec/UnsetMapFlagEncoder.js';
import UpdateFriendListEncoder from '#/network/rs225/server/codec/UpdateFriendListEncoder.js';
import UpdateIgnoreListEncoder from '#/network/rs225/server/codec/UpdateIgnoreListEncoder.js';
import UpdateInvFullEncoder from '#/network/rs225/server/codec/UpdateInvFullEncoder.js';
import UpdateInvPartialEncoder from '#/network/rs225/server/codec/UpdateInvPartialEncoder.js';
import UpdateInvStopTransmitEncoder from '#/network/rs225/server/codec/UpdateInvStopTransmitEncoder.js';
import UpdatePidEncoder from '#/network/rs225/server/codec/UpdatePidEncoder.js';
import UpdateRebootTimerEncoder from '#/network/rs225/server/codec/UpdateRebootTimerEncoder.js';
import UpdateRunEnergyEncoder from '#/network/rs225/server/codec/UpdateRunEnergyEncoder.js';
import UpdateRunWeightEncoder from '#/network/rs225/server/codec/UpdateRunWeightEncoder.js';
import UpdateStatEncoder from '#/network/rs225/server/codec/UpdateStatEncoder.js';
import UpdateZoneFullFollowsEncoder from '#/network/rs225/server/codec/UpdateZoneFullFollowsEncoder.js';
import UpdateZonePartialEnclosedEncoder from '#/network/rs225/server/codec/UpdateZonePartialEnclosedEncoder.js';
import UpdateZonePartialFollowsEncoder from '#/network/rs225/server/codec/UpdateZonePartialFollowsEncoder.js';
import VarpLargeEncoder from '#/network/rs225/server/codec/VarpLargeEncoder.js';
import VarpSmallEncoder from '#/network/rs225/server/codec/VarpSmallEncoder.js';
import InfoMessageEncoder from '#/network/server/codec/InfoMessageEncoder.js';
import MessageEncoder from '#/network/server/codec/MessageEncoder.js';
import ZoneMessageEncoder from '#/network/server/codec/ZoneMessageEncoder.js';
import InfoMessage from '#/network/server/InfoMessage.js';
import CamLookAt from '#/network/server/model/CamLookAt.js';
import CamMoveTo from '#/network/server/model/CamMoveTo.js';
import CamReset from '#/network/server/model/CamReset.js';
import CamShake from '#/network/server/model/CamShake.js';
import ChatFilterSettings from '#/network/server/model/ChatFilterSettings.js';
import DataLand from '#/network/server/model/DataLand.js';
import DataLandDone from '#/network/server/model/DataLandDone.js';
import DataLoc from '#/network/server/model/DataLoc.js';
import DataLocDone from '#/network/server/model/DataLocDone.js';
import EnableTracking from '#/network/server/model/EnableTracking.js';
import FinishTracking from '#/network/server/model/FinishTracking.js';
import HintArrow from '#/network/server/model/HintArrow.js';
import IfClose from '#/network/server/model/IfClose.js';
import IfOpenChat from '#/network/server/model/IfOpenChat.js';
import IfOpenMain from '#/network/server/model/IfOpenMain.js';
import IfOpenMainSide from '#/network/server/model/IfOpenMainSide.js';
import IfOpenSide from '#/network/server/model/IfOpenSide.js';
import IfSetAnim from '#/network/server/model/IfSetAnim.js';
import IfSetColour from '#/network/server/model/IfSetColour.js';
import IfSetHide from '#/network/server/model/IfSetHide.js';
import IfSetModel from '#/network/server/model/IfSetModel.js';
import IfSetNpcHead from '#/network/server/model/IfSetNpcHead.js';
import IfSetObject from '#/network/server/model/IfSetObject.js';
import IfSetPlayerHead from '#/network/server/model/IfSetPlayerHead.js';
import IfSetPosition from '#/network/server/model/IfSetPosition.js';
import IfSetRecol from '#/network/server/model/IfSetRecol.js';
import IfSetTab from '#/network/server/model/IfSetTab.js';
import IfSetTabActive from '#/network/server/model/IfSetTabActive.js';
import IfSetText from '#/network/server/model/IfSetText.js';
import LastLoginInfo from '#/network/server/model/LastLoginInfo.js';
import LocAddChange from '#/network/server/model/LocAddChange.js';
import LocAnim from '#/network/server/model/LocAnim.js';
import LocDel from '#/network/server/model/LocDel.js';
import LocMerge from '#/network/server/model/LocMerge.js';
import Logout from '#/network/server/model/Logout.js';
import MapAnim from '#/network/server/model/MapAnim.js';
import MapProjAnim from '#/network/server/model/MapProjAnim.js';
import MessageGame from '#/network/server/model/MessageGame.js';
import MessagePrivate from '#/network/server/model/MessagePrivate.js';
import MidiJingle from '#/network/server/model/MidiJingle.js';
import MidiSong from '#/network/server/model/MidiSong.js';
import NpcInfo from '#/network/server/model/NpcInfo.js';
import NpcInfoAnim from '#/network/server/model/NpcInfoAnim.js';
import NpcInfoChangeType from '#/network/server/model/NpcInfoChangeType.js';
import NpcInfoDamage from '#/network/server/model/NpcInfoDamage.js';
import NpcInfoFaceCoord from '#/network/server/model/NpcInfoFaceCoord.js';
import NpcInfoFaceEntity from '#/network/server/model/NpcInfoFaceEntity.js';
import NpcInfoSay from '#/network/server/model/NpcInfoSay.js';
import NpcInfoSpotanim from '#/network/server/model/NpcInfoSpotanim.js';
import ObjAdd from '#/network/server/model/ObjAdd.js';
import ObjCount from '#/network/server/model/ObjCount.js';
import ObjDel from '#/network/server/model/ObjDel.js';
import ObjReveal from '#/network/server/model/ObjReveal.js';
import PCountDialog from '#/network/server/model/PCountDialog.js';
import PlayerInfo from '#/network/server/model/PlayerInfo.js';
import PlayerInfoAnim from '#/network/server/model/PlayerInfoAnim.js';
import PlayerInfoAppearance from '#/network/server/model/PlayerInfoAppearance.js';
import PlayerInfoChat from '#/network/server/model/PlayerInfoChat.js';
import PlayerInfoDamage from '#/network/server/model/PlayerInfoDamage.js';
import PlayerInfoExactMove from '#/network/server/model/PlayerInfoExactMove.js';
import PlayerInfoFaceCoord from '#/network/server/model/PlayerInfoFaceCoord.js';
import PlayerInfoFaceEntity from '#/network/server/model/PlayerInfoFaceEntity.js';
import PlayerInfoSay from '#/network/server/model/PlayerInfoSay.js';
import PlayerInfoSpotanim from '#/network/server/model/PlayerInfoSpotanim.js';
import RebuildNormal from '#/network/server/model/RebuildNormal.js';
import ResetAnims from '#/network/server/model/ResetAnims.js';
import ResetClientVarCache from '#/network/server/model/ResetClientVarCache.js';
import SetMultiway from '#/network/server/model/SetMultiway.js';
import SynthSound from '#/network/server/model/SynthSound.js';
import TutFlash from '#/network/server/model/TutFlash.js';
import TutOpen from '#/network/server/model/TutOpen.js';
import UnsetMapFlag from '#/network/server/model/UnsetMapFlag.js';
import UpdateFriendList from '#/network/server/model/UpdateFriendList.js';
import UpdateIgnoreList from '#/network/server/model/UpdateIgnoreList.js';
import UpdateInvFull from '#/network/server/model/UpdateInvFull.js';
import UpdateInvPartial from '#/network/server/model/UpdateInvPartial.js';
import UpdateInvStopTransmit from '#/network/server/model/UpdateInvStopTransmit.js';
import UpdateUid192 from '#/network/server/model/UpdatePid.js';
import UpdateRebootTimer from '#/network/server/model/UpdateRebootTimer.js';
import UpdateRunEnergy from '#/network/server/model/UpdateRunEnergy.js';
import UpdateRunWeight from '#/network/server/model/UpdateRunWeight.js';
import UpdateStat from '#/network/server/model/UpdateStat.js';
import UpdateZoneFullFollows from '#/network/server/model/UpdateZoneFullFollows.js';
import UpdateZonePartialEnclosed from '#/network/server/model/UpdateZonePartialEnclosed.js';
import UpdateZonePartialFollows from '#/network/server/model/UpdateZonePartialFollows.js';
import VarpLarge from '#/network/server/model/VarpLarge.js';
import VarpSmall from '#/network/server/model/VarpSmall.js';
import OutgoingMessage from '#/network/server/OutgoingMessage.js';
import ZoneMessage from '#/network/server/ZoneMessage.js';

/* eslint-disable @typescript-eslint/no-explicit-any */
type GenericOutgoingMessage<T extends OutgoingMessage> = new (...args: any[]) => T;

class ServerProtRepository {
    private encoders: Map<GenericOutgoingMessage<OutgoingMessage>, MessageEncoder<OutgoingMessage>> = new Map();

    private bind<T extends OutgoingMessage>(message: GenericOutgoingMessage<T>, encoder: MessageEncoder<T>) {
        if (this.encoders.has(message)) {
            throw new Error(`[ServerProtRepository] Already defines a ${message.name}.`);
        }
        this.encoders.set(message, encoder);
    }

    constructor() {
        this.bind(CamLookAt, new CamLookAtEncoder());
        this.bind(CamMoveTo, new CamMoveToEncoder());
        this.bind(CamReset, new CamResetEncoder());
        this.bind(CamShake, new CamShakeEncoder());
        this.bind(ChatFilterSettings, new ChatFilterSettingsEncoder());
        this.bind(DataLand, new DataLandEncoder());
        this.bind(DataLandDone, new DataLandDoneEncoder());
        this.bind(DataLoc, new DataLocEncoder());
        this.bind(DataLocDone, new DataLocDoneEncoder());
        this.bind(EnableTracking, new EnableTrackingEncoder());
        this.bind(FinishTracking, new FinishTrackingEncoder());
        this.bind(HintArrow, new HintArrowEncoder());
        this.bind(IfClose, new IfCloseEncoder());
        this.bind(IfOpenChat, new IfOpenChatEncoder());
        this.bind(IfOpenMain, new IfOpenMainEncoder());
        this.bind(IfOpenMainSide, new IfOpenMainSideEncoder());
        this.bind(IfOpenSide, new IfOpenSideEncoder());
        this.bind(IfSetTab, new IfSetTabEncoder());
        this.bind(IfSetAnim, new IfSetAnimEncoder());
        this.bind(IfSetColour, new IfSetColourEncoder());
        this.bind(IfSetHide, new IfSetHideEncoder());
        this.bind(IfSetModel, new IfSetModelEncoder());
        this.bind(IfSetNpcHead, new IfSetNpcHeadEncoder());
        this.bind(IfSetObject, new IfSetObjectEncoder());
        this.bind(IfSetPlayerHead, new IfSetPlayerHeadEncoder());
        this.bind(IfSetPosition, new IfSetPositionEncoder());
        this.bind(IfSetRecol, new IfSetRecolEncoder());
        this.bind(IfSetText, new IfSetTextEncoder());
        this.bind(IfSetTabActive, new IfSetTabActiveEncoder());
        this.bind(LastLoginInfo, new LastLoginInfoEncoder());
        this.bind(LocAddChange, new LocAddChangeEncoder());
        this.bind(LocAnim, new LocAnimEncoder());
        this.bind(LocDel, new LocDelEncoder());
        this.bind(LocMerge, new LocMergeEncoder());
        this.bind(Logout, new LogoutEncoder());
        this.bind(MapAnim, new MapAnimEncoder());
        this.bind(MapProjAnim, new MapProjAnimEncoder());
        this.bind(MessageGame, new MessageGameEncoder());
        this.bind(MessagePrivate, new MessagePrivateEncoder());
        this.bind(MidiJingle, new MidiJingleEncoder());
        this.bind(MidiSong, new MidiSongEncoder());
        this.bind(NpcInfo, new NpcInfoEncoder());
        this.bind(ObjAdd, new ObjAddEncoder());
        this.bind(ObjCount, new ObjCountEncoder());
        this.bind(ObjDel, new ObjDelEncoder());
        this.bind(ObjReveal, new ObjRevealEncoder());
        this.bind(PCountDialog, new PCountDialogEncoder());
        this.bind(PlayerInfo, new PlayerInfoEncoder());
        this.bind(RebuildNormal, new RebuildNormalEncoder());
        this.bind(ResetAnims, new ResetAnimsEncoder());
        this.bind(ResetClientVarCache, new ResetClientVarCacheEncoder());
        this.bind(SetMultiway, new SetMultiwayEncoder());
        this.bind(SynthSound, new SynthSoundEncoder());
        this.bind(TutFlash, new TutFlashEncoder());
        this.bind(TutOpen, new TutOpenEncoder());
        this.bind(UnsetMapFlag, new UnsetMapFlagEncoder());
        this.bind(UpdateFriendList, new UpdateFriendListEncoder());
        this.bind(UpdateIgnoreList, new UpdateIgnoreListEncoder());
        this.bind(UpdateInvFull, new UpdateInvFullEncoder());
        this.bind(UpdateInvPartial, new UpdateInvPartialEncoder());
        this.bind(UpdateInvStopTransmit, new UpdateInvStopTransmitEncoder());
        this.bind(UpdateRunEnergy, new UpdateRunEnergyEncoder());
        this.bind(UpdateRunWeight, new UpdateRunWeightEncoder());
        this.bind(UpdateRebootTimer, new UpdateRebootTimerEncoder());
        this.bind(UpdateStat, new UpdateStatEncoder());
        this.bind(UpdateUid192, new UpdatePidEncoder());
        this.bind(UpdateZoneFullFollows, new UpdateZoneFullFollowsEncoder());
        this.bind(UpdateZonePartialEnclosed, new UpdateZonePartialEnclosedEncoder());
        this.bind(UpdateZonePartialFollows, new UpdateZonePartialFollowsEncoder());
        this.bind(VarpLarge, new VarpLargeEncoder());
        this.bind(VarpSmall, new VarpSmallEncoder());
        // ---- player_info
        this.bind(PlayerInfoAnim, new PlayerInfoAnimEncoder());
        this.bind(PlayerInfoAppearance, new PlayerInfoAppearanceEncoder());
        this.bind(PlayerInfoChat, new PlayerInfoChatEncoder());
        this.bind(PlayerInfoDamage, new PlayerInfoDamageEncoder());
        this.bind(PlayerInfoFaceCoord, new PlayerInfoFaceCoordEncoder());
        this.bind(PlayerInfoFaceEntity, new PlayerInfoFaceEntityEncoder());
        this.bind(PlayerInfoSay, new PlayerInfoSayEncoder());
        this.bind(PlayerInfoSpotanim, new PlayerInfoSpotanimEncoder());
        this.bind(PlayerInfoExactMove, new PlayerInfoExactMoveEncoder());
        // ---- npc_info
        this.bind(NpcInfoAnim, new NpcInfoAnimEncoder());
        this.bind(NpcInfoChangeType, new NpcInfoChangeTypeEncoder());
        this.bind(NpcInfoDamage, new NpcInfoDamageEncoder());
        this.bind(NpcInfoFaceCoord, new NpcInfoFaceCoordEncoder());
        this.bind(NpcInfoFaceEntity, new NpcInfoFaceEntityEncoder());
        this.bind(NpcInfoSay, new NpcInfoSayEncoder());
        this.bind(NpcInfoSpotanim, new NpcInfoSpotanimEncoder());
    }

    getEncoder<T extends OutgoingMessage>(message: T): MessageEncoder<T> | undefined {
        return this.encoders.get(message.constructor as GenericOutgoingMessage<T>);
    }

    getZoneEncoder<T extends ZoneMessage>(message: T): ZoneMessageEncoder<T> | undefined {
        return this.encoders.get(message.constructor as GenericOutgoingMessage<T>) as ZoneMessageEncoder<T> | undefined;
    }

    getInfoEncoder<T extends InfoMessage>(message: T): InfoMessageEncoder<T> | undefined {
        return this.encoders.get(message.constructor as GenericOutgoingMessage<T>) as InfoMessageEncoder<T> | undefined;
    }
}

export default new ServerProtRepository();
