export enum ClientProt {
    REBUILD_GETMAPS = 150, // index: 4

    IDLE_TIMER = 70, // index: 6

    NO_TIMEOUT = 108, // index: 30 - NXT naming

    EVENT_TRACKING = 81, // index: 34
    EVENT_CAMERA_POSITION = 189, // index: 35 - NXT naming

    // autogenerated as part of obfuscation process
    ANTICHEAT_OPLOGIC1 = 7, // index: 60
    ANTICHEAT_OPLOGIC2 = 88, // index: 61
    ANTICHEAT_OPLOGIC3 = 30, // index: 62
    ANTICHEAT_OPLOGIC4 = 176, // index: 63
    ANTICHEAT_OPLOGIC5 = 220, // index: 64
    ANTICHEAT_OPLOGIC6 = 66, // index: 65
    ANTICHEAT_OPLOGIC7 = 17, // index: 66
    ANTICHEAT_OPLOGIC8 = 2, // index: 67
    ANTICHEAT_OPLOGIC9 = 238, // index: 68

    // autogenerated as part of obfuscation process
    ANTICHEAT_CYCLELOGIC1 = 233, // index: 70
    ANTICHEAT_CYCLELOGIC2 = 146, // index: 71
    ANTICHEAT_CYCLELOGIC3 = 215, // index: 74
    ANTICHEAT_CYCLELOGIC4 = 236, // index: 72
    ANTICHEAT_CYCLELOGIC5 = 85, // index: 75
    ANTICHEAT_CYCLELOGIC6 = 219, // index: 73

    OPOBJ1 = 140, // index: 80 - NXT naming
    OPOBJ2 = 40, // index: 81 - NXT naming
    OPOBJ3 = 200, // index: 82 - NXT naming
    OPOBJ4 = 178, // index: 83 - NXT naming
    OPOBJ5 = 247, // index: 84 - NXT naming
    OPOBJT = 138, // index: 88 - NXT naming
    OPOBJU = 239, // index: 89 - NXT naming

    OPNPC1 = 194, // index: 100 - NXT naming
    OPNPC2 = 8, // index: 101 - NXT naming
    OPNPC3 = 27, // index: 102 - NXT naming
    OPNPC4 = 113, // index: 103 - NXT naming
    OPNPC5 = 100, // index: 104 - NXT naming
    OPNPCT = 134, // index: 108 - NXT naming
    OPNPCU = 202, // index: 109 - NXT naming

    OPLOC1 = 245, // index: 120 - NXT naming
    OPLOC2 = 172, // index: 121 - NXT naming
    OPLOC3 = 96, // index: 122 - NXT naming
    OPLOC4 = 97, // index: 123 - NXT naming
    OPLOC5 = 116, // index: 124 - NXT naming
    OPLOCT = 9, // index: 128 - NXT naming
    OPLOCU = 75, // index: 129 - NXT naming

    OPPLAYER1 = 164, // index: 140 - NXT naming
    OPPLAYER2 = 53, // index: 141 - NXT naming
    OPPLAYER3 = 185, // index: 142 - NXT naming
    OPPLAYER4 = 206, // index: 143 - NXT naming
    OPPLAYERT = 177, // index: 148 - NXT naming
    OPPLAYERU = 248, // index: 149 - NXT naming

    OPHELD1 = 195, // index: 160 - name based on runescript trigger
    OPHELD2 = 71, // index: 161 - name based on runescript trigger
    OPHELD3 = 133, // index: 162 - name based on runescript trigger
    OPHELD4 = 157, // index: 163 - name based on runescript trigger
    OPHELD5 = 211, // index: 164 - name based on runescript trigger
    OPHELDT = 48, // index: 168 - name based on runescript trigger
    OPHELDU = 130, // index: 169 - name based on runescript trigger

    INV_BUTTON1 = 31, // index: 190 - NXT has "IF_BUTTON1" but for our interface system, this makes more sense
    INV_BUTTON2 = 59, // index: 191 - NXT has "IF_BUTTON2" but for our interface system, this makes more sense
    INV_BUTTON3 = 212, // index: 192 - NXT has "IF_BUTTON3" but for our interface system, this makes more sense
    INV_BUTTON4 = 38, // index: 193 - NXT has "IF_BUTTON4" but for our interface system, this makes more sense
    INV_BUTTON5 = 6, // index: 194 - NXT has "IF_BUTTON5" but for our interface system, this makes more sense
    IF_BUTTON = 155, // index: 200 - NXT naming

    RESUME_PAUSEBUTTON = 235, // index: 201 - NXT naming
    CLOSE_MODAL = 231, // index: 202 - NXT naming
    RESUME_P_COUNTDIALOG = 237, // index: 203 - NXT naming
    TUTORIAL_CLICKSIDE = 175, // index: 204

    MOVE_OPCLICK = 93, // index: 242 - comes with OP packets, name based on other MOVE packets
    BUG_REPORT = 190, // index: 243 - NXT naming
    MOVE_MINIMAPCLICK = 165, // index: 244 - NXT naming
    INV_BUTTOND = 159, // index: 245 - NXT has "IF_BUTTOND" but for our interface system, this makes more sense
    IGNORELIST_DEL = 171, // index: 246 - NXT naming
    IGNORELIST_ADD = 79, // index: 247 - NXT naming
    IF_PLAYERDESIGN = 52, // index: 248
    CHAT_SETMODE = 244, // index: 249 - NXT naming
    MESSAGE_PRIVATE = 148, // index: 250 - NXT naming
    FRIENDLIST_DEL = 11, // index: 251 - NXT naming
    FRIENDLIST_ADD = 118, // index: 252 - NXT naming
    CLIENT_CHEAT = 4, // index: 253 - NXT naming
    MESSAGE_PUBLIC = 158, // index: 254 - NXT naming
    MOVE_GAMECLICK = 181, // index: 255 - NXT naming
}

export const ClientProtLengths: number[] = [];

ClientProtLengths[ClientProt.REBUILD_GETMAPS] = -1;

ClientProtLengths[ClientProt.IDLE_TIMER] = 0;

ClientProtLengths[ClientProt.NO_TIMEOUT] = 0;

ClientProtLengths[ClientProt.EVENT_TRACKING] = -2;
ClientProtLengths[ClientProt.EVENT_CAMERA_POSITION] = 6;

ClientProtLengths[ClientProt.ANTICHEAT_OPLOGIC1] = 4;
ClientProtLengths[ClientProt.ANTICHEAT_OPLOGIC2] = 4;
ClientProtLengths[ClientProt.ANTICHEAT_OPLOGIC3] = 3;
ClientProtLengths[ClientProt.ANTICHEAT_OPLOGIC4] = 2;
ClientProtLengths[ClientProt.ANTICHEAT_OPLOGIC5] = 0;
ClientProtLengths[ClientProt.ANTICHEAT_OPLOGIC6] = 4;
ClientProtLengths[ClientProt.ANTICHEAT_OPLOGIC7] = 4;
ClientProtLengths[ClientProt.ANTICHEAT_OPLOGIC8] = 2;
ClientProtLengths[ClientProt.ANTICHEAT_OPLOGIC9] = 1;

ClientProtLengths[ClientProt.ANTICHEAT_CYCLELOGIC1] = 1;
ClientProtLengths[ClientProt.ANTICHEAT_CYCLELOGIC2] = -1;
ClientProtLengths[ClientProt.ANTICHEAT_CYCLELOGIC3] = 3;
ClientProtLengths[ClientProt.ANTICHEAT_CYCLELOGIC4] = 4;
ClientProtLengths[ClientProt.ANTICHEAT_CYCLELOGIC5] = 0;
ClientProtLengths[ClientProt.ANTICHEAT_CYCLELOGIC6] = -1;

ClientProtLengths[ClientProt.OPOBJ1] = 6;
ClientProtLengths[ClientProt.OPOBJ2] = 6;
ClientProtLengths[ClientProt.OPOBJ3] = 6;
ClientProtLengths[ClientProt.OPOBJ4] = 6;
ClientProtLengths[ClientProt.OPOBJ5] = 6;
ClientProtLengths[ClientProt.OPOBJT] = 8;
ClientProtLengths[ClientProt.OPOBJU] = 12;

ClientProtLengths[ClientProt.OPNPC1] = 2;
ClientProtLengths[ClientProt.OPNPC2] = 2;
ClientProtLengths[ClientProt.OPNPC3] = 2;
ClientProtLengths[ClientProt.OPNPC4] = 2;
ClientProtLengths[ClientProt.OPNPC5] = 2;
ClientProtLengths[ClientProt.OPNPCT] = 4;
ClientProtLengths[ClientProt.OPNPCU] = 8;

ClientProtLengths[ClientProt.OPLOC1] = 6;
ClientProtLengths[ClientProt.OPLOC2] = 6;
ClientProtLengths[ClientProt.OPLOC3] = 6;
ClientProtLengths[ClientProt.OPLOC4] = 6;
ClientProtLengths[ClientProt.OPLOC5] = 6;
ClientProtLengths[ClientProt.OPLOCT] = 8;
ClientProtLengths[ClientProt.OPLOCU] = 12;

ClientProtLengths[ClientProt.OPPLAYER1] = 2;
ClientProtLengths[ClientProt.OPPLAYER2] = 2;
ClientProtLengths[ClientProt.OPPLAYER3] = 2;
ClientProtLengths[ClientProt.OPPLAYER4] = 2;
ClientProtLengths[ClientProt.OPPLAYERT] = 4;
ClientProtLengths[ClientProt.OPPLAYERU] = 8;

ClientProtLengths[ClientProt.OPHELD1] = 6;
ClientProtLengths[ClientProt.OPHELD2] = 6;
ClientProtLengths[ClientProt.OPHELD3] = 6;
ClientProtLengths[ClientProt.OPHELD4] = 6;
ClientProtLengths[ClientProt.OPHELD5] = 6;
ClientProtLengths[ClientProt.OPHELDT] = 8;
ClientProtLengths[ClientProt.OPHELDU] = 12;

ClientProtLengths[ClientProt.INV_BUTTON1] = 6;
ClientProtLengths[ClientProt.INV_BUTTON2] = 6;
ClientProtLengths[ClientProt.INV_BUTTON3] = 6;
ClientProtLengths[ClientProt.INV_BUTTON4] = 6;
ClientProtLengths[ClientProt.INV_BUTTON5] = 6;
ClientProtLengths[ClientProt.IF_BUTTON] = 2;

ClientProtLengths[ClientProt.RESUME_PAUSEBUTTON] = 2;
ClientProtLengths[ClientProt.CLOSE_MODAL] = 0;
ClientProtLengths[ClientProt.RESUME_P_COUNTDIALOG] = 4;
ClientProtLengths[ClientProt.TUTORIAL_CLICKSIDE] = 1;

ClientProtLengths[ClientProt.MOVE_OPCLICK] = -1;
ClientProtLengths[ClientProt.BUG_REPORT] = 10;
ClientProtLengths[ClientProt.MOVE_MINIMAPCLICK] = -1;
ClientProtLengths[ClientProt.INV_BUTTOND] = 6;
ClientProtLengths[ClientProt.IGNORELIST_DEL] = 8;
ClientProtLengths[ClientProt.IGNORELIST_ADD] = 8;
ClientProtLengths[ClientProt.IF_PLAYERDESIGN] = 13;
ClientProtLengths[ClientProt.CHAT_SETMODE] = 3;
ClientProtLengths[ClientProt.MESSAGE_PRIVATE] = -1;
ClientProtLengths[ClientProt.FRIENDLIST_DEL] = 8;
ClientProtLengths[ClientProt.FRIENDLIST_ADD] = 8;
ClientProtLengths[ClientProt.CLIENT_CHEAT] = -1;
ClientProtLengths[ClientProt.MESSAGE_PUBLIC] = -1;
ClientProtLengths[ClientProt.MOVE_GAMECLICK] = -1;
