export const ServerProt = {
    IF_SETCOLOUR: 2,
    IF_OPENCHAT: 14,
    IF_OPENMAINMODALSIDEOVERLAY: 28, // ugh
    IF_SETHIDE: 26,
    IF_SETOBJECT: 46,
    IF_SETTAB_ACTIVE: 84,
    IF_SETMODEL: 87,
    IF_SETMODEL_COLOUR: 103,
    IF_SETTAB_FLASH: 126,
    IF_CLOSE: 129,
    IF_SETANIM: 146,
    IF_SETTAB: 167,
    IF_OPENMAINMODAL: 168,
    IF_OPENCHATSTICKY: 185,
    IF_OPENSIDEOVERLAY: 195,
    IF_SETPLAYERHEAD: 197,
    IF_SETTEXT: 201,
    IF_SETNPCHEAD: 204,
    IF_SETPOSITION: 209,
    IF_IAMOUNT: 243,
    IF_MULTIZONE: 254,

    UPDATE_INV_CLEAR: 15,
    UPDATE_INV_FULL: 98,
    UPDATE_INV_PARTIAL: 213,

    CAM_LOOKAT: 3,
    CAM_SHAKE: 13,
    CAM_MOVETO: 74,
    CAM_RESET: 239,

    NPC_INFO: 1,
    PLAYER_INFO: 184,

    CLEAR_WALKING_QUEUE: 19,
    UPDATE_RUNWEIGHT: 22,
    HINT_ARROW: 25,
    UPDATE_REBOOT_TIMER: 43,
    UPDATE_STAT: 44,
    UPDATE_RUNENERGY: 68,
    FINISH_TRACKING: 133,
    RESET_ANIMS: 136,
    UPDATE_UID192: 139,
    LAST_LOGIN_INFO: 140,
    LOGOUT: 142,
    ENABLE_TRACKING: 226,
    MESSAGE_GAME: 4,
    UPDATE_IGNORELIST: 21,
    CHAT_FILTER_SETTINGS: 32,
    MESSAGE_PRIVATE: 41,
    UPDATE_FRIENDLIST: 152,

    DATA_LOC_DONE: 20,
    DATA_LAND_DONE: 80,
    DATA_LAND: 132,
    DATA_LOC: 220,
    LOAD_AREA: 237,

    VARP_SMALL: 150,
    VARP_LARGE: 175,
    RESET_CLIENT_VARCACHE: 193,

    SYNTH_SOUND: 12,
    MIDI_SONG: 54,
    MIDI_JINGLE: 212,

    UPDATE_ZONE_PARTIAL_FOLLOWS: 7,
    UPDATE_ZONE_FULL_FOLLOWS: 135,
    UPDATE_ZONE_PARTIAL_ENCLOSED: 162,

    LOC_MERGE: 23,
    LOC_ANIM: 42,
    OBJ_DEL: 49,
    OBJ_REVEAL: 50,
    LOC_ADD_CHANGE: 59,
    MAP_PROJANIM: 69,
    LOC_DEL: 76,
    OBJ_COUNT: 151,
    MAP_ANIM: 191,
    OBJ_ADD: 223
};

// generate reverse lookup:
export const ServerProtNames: Record<number, string> = {};
Object.keys(ServerProt).forEach((key: keyof typeof ServerProt) => ServerProtNames[ServerProt[key]] = key);
