name: Deploy to servers

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy-world1:
    name: Deploy to World 1 (Free) server
    runs-on: ubuntu-latest
    steps:
    - name: Executing commands over SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_WORLD1_HOST }}
        username: ${{ secrets.SSH_WORLD1_USER }}
        key: ${{ secrets.SSH_WORLD1_KEY }}
        port: ${{ secrets.SSH_WORLD1_PORT }}
        script: cd /opt/2004scape/Server && pm2 stop all && git pull && npm ci && npm run client:clean && npm run client:pack && npm run server:clean && npm run server:build && pm2 start all

  deploy-world2:
    name: Deploy to World 2 (Members) server
    runs-on: ubuntu-latest
    steps:
    - name: Executing commands over SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_WORLD2_HOST }}
        username: ${{ secrets.SSH_WORLD2_USER }}
        key: ${{ secrets.SSH_WORLD2_KEY }}
        port: ${{ secrets.SSH_WORLD2_PORT }}
        script: cd /opt/2004scape/Server && pm2 stop all && git pull && npm ci && npm run client:clean && npm run client:pack && npm run server:clean && npm run server:build && pm2 start all
