name: Lint Engine Code

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, live ]
    paths:
      - '.github/workflows/engine-lint.yml'
      - 'src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: npm i

    - name: Run Linter
      run: npm run lint
