name: Test Engine Code

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, live ]
    paths:
      - '.github/workflows/engine-test.yml'
      - 'src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install Dependencies
      run: npm i

    - name: Run tests
      run: CI_MODE=true npm test