name: Deploy World
env: ${{ secrets }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

# pm2 start npm --name "world1" --kill-timeout 600000 -- run quickstart
# pm2 start npm --name "world1-maintenance" -- run maintenance

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}

    steps:
    - name: Checkout Client-TS
      uses: actions/checkout@v4
      with:
        repository: 'LostCityRS/Client-TS'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Build Client-TS
      run: |
        bun install
        bun run rsa.ts
        echo "SECURE_ORIGIN=${{ secrets.SECURE_ORIGIN }}" >> .env
        bun run build:uglify

    - name: Download Packed Data
      uses: actions/download-artifact@v4
      with:
        name: packed

    - name: Shutdown World
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          pm2 stop ${{ inputs.environment }}
          pm2 start ${{ inputs.environment }}-maintenance
          cd ${{ inputs.environment }}
          git reset --hard
          git pull
          npm i

    - name: Update Content
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "client,server"
        target: ${{ inputs.environment }}/data/pack
        rm: true

    - name: Update RSA
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "private.pem"
        target: ${{ inputs.environment }}/data/config

    - name: Update Client
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "out"
        target: ${{ inputs.environment }}/public/client
        strip_components: 1

    - name: Start World
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          pm2 stop ${{ inputs.environment}}-maintenance
          pm2 start ${{ inputs.environment}}
